package com.example.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme Colors
val primaryLight = Color(0xFF6366F1) // Premium Indigo
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEEF2FF) // Soft indigo highlight
val onPrimaryContainerLight = Color(0xFF4F46E5)
val secondaryLight = Color(0xFF0D9488) // Emerald Teal
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF0FDF4)
val onSecondaryContainerLight = Color(0xFF166534)
val tertiaryLight = Color(0xFFD946EF) // Pink/Fuchsia
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFDF4FF)
val onTertiaryContainerLight = Color(0xFF86198F)
val errorLight = Color(0xFFEF4444)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEE2E2)
val onErrorContainerLight = Color(0xFF991B1B)
val backgroundLight = Color(0xFFF8FAFC) // Slate 50
val onBackgroundLight = Color(0xFF0F172A) // Slate 900
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF0F172A)
val surfaceVariantLight = Color(0xFFF1F5F9)
val onSurfaceVariantLight = Color(0xFF475569)
val outlineLight = Color(0xFF94A3B8)
val outlineVariantLight = Color(0xFFE2E8F0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1E293B)
val inverseOnSurfaceLight = Color(0xFFF8FAFC)
val inversePrimaryLight = Color(0xFFC7D2FE)
val surfaceDimLight = Color(0xFFE2E8F0)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8FAFC)
val surfaceContainerLight = Color(0xFFF1F5F9)
val surfaceContainerHighLight = Color(0xFFE2E8F0)
val surfaceContainerHighestLight = Color(0xFFCBD5E1)

// Dark Scheme Colors
val primaryDark = Color(0xFF818CF8) // Glowing Indigo
val onPrimaryDark = Color(0xFF0F172A)
val primaryContainerDark = Color(0xFF312E81) // Deep Indigo
val onPrimaryContainerDark = Color(0xFFE0E7FF)
val secondaryDark = Color(0xFF2DD4BF) // Bright Neon Teal
val onSecondaryDark = Color(0xFF0F172A)
val secondaryContainerDark = Color(0xFF115E59)
val onSecondaryContainerDark = Color(0xFFCCFBF1)
val tertiaryDark = Color(0xFFF472B6) // Vibrant Pink
val onTertiaryDark = Color(0xFF500724)
val tertiaryContainerDark = Color(0xFF881337)
val onTertiaryContainerDark = Color(0xFFFCE7F3)
val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF7F1D1D)
val errorContainerDark = Color(0xFF991B1B)
val onErrorContainerDark = Color(0xFFFEE2E2)
val backgroundDark = Color(0xFF0B0F19) // Deep Midnight Blue
val onBackgroundDark = Color(0xFFF1F5F9)
val surfaceDark = Color(0xFF151D30) // Dark Indigo-Slate Card surface
val onSurfaceDark = Color(0xFFF1F5F9)
val surfaceVariantDark = Color(0xFF1E293B)
val onSurfaceVariantDark = Color(0xFFCBD5E1)
val outlineDark = Color(0xFF475569)
val outlineVariantDark = Color(0xFF334155)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF8FAFC)
val inverseOnSurfaceDark = Color(0xFF0F172A)
val inversePrimaryDark = Color(0xFF4F46E5)
val surfaceDimDark = Color(0xFF0B0F19)
val surfaceBrightDark = Color(0xFF1E293B)
val surfaceContainerLowestDark = Color(0xFF05070C)
val surfaceContainerLowDark = Color(0xFF0F1424)
val surfaceContainerDark = Color(0xFF151D30)
val surfaceContainerHighDark = Color(0xFF1E293B)
val surfaceContainerHighestDark = Color(0xFF334155)

// Medium Contrast / High Contrast placeholders required for Theme compilation mapping
val primaryLightMediumContrast = primaryLight
val onPrimaryLightMediumContrast = onPrimaryLight
val primaryContainerLightMediumContrast = primaryContainerLight
val onPrimaryContainerLightMediumContrast = onPrimaryContainerLight
val secondaryLightMediumContrast = secondaryLight
val onSecondaryLightMediumContrast = onSecondaryLight
val secondaryContainerLightMediumContrast = secondaryContainerLight
val onSecondaryContainerLightMediumContrast = onSecondaryContainerLight
val tertiaryLightMediumContrast = tertiaryLight
val onTertiaryLightMediumContrast = onTertiaryLight
val tertiaryContainerLightMediumContrast = tertiaryContainerLight
val onTertiaryContainerLightMediumContrast = onTertiaryContainerLight
val errorLightMediumContrast = errorLight
val onErrorLightMediumContrast = onErrorLight
val errorContainerLightMediumContrast = errorContainerLight
val onErrorContainerLightMediumContrast = onErrorContainerLight
val backgroundLightMediumContrast = backgroundLight
val onBackgroundLightMediumContrast = onBackgroundLight
val surfaceLightMediumContrast = surfaceLight
val onSurfaceLightMediumContrast = onSurfaceLight
val surfaceVariantLightMediumContrast = surfaceVariantLight
val onSurfaceVariantLightMediumContrast = onSurfaceVariantLight
val outlineLightMediumContrast = outlineLight
val outlineVariantLightMediumContrast = outlineVariantLight
val scrimLightMediumContrast = scrimLight
val inverseSurfaceLightMediumContrast = inverseSurfaceLight
val inverseOnSurfaceLightMediumContrast = inverseOnSurfaceLight
val inversePrimaryLightMediumContrast = inversePrimaryLight
val surfaceDimLightMediumContrast = surfaceDimLight
val surfaceBrightLightMediumContrast = surfaceBrightLight
val surfaceContainerLowestLightMediumContrast = surfaceContainerLowestLight
val surfaceContainerLowLightMediumContrast = surfaceContainerLowLight
val surfaceContainerLightMediumContrast = surfaceContainerLight
val surfaceContainerHighLightMediumContrast = surfaceContainerHighLight
val surfaceContainerHighestLightMediumContrast = surfaceContainerHighestLight

val primaryLightHighContrast = primaryLight
val onPrimaryLightHighContrast = onPrimaryLight
val primaryContainerLightHighContrast = primaryContainerLight
val onPrimaryContainerLightHighContrast = onPrimaryContainerLight
val secondaryLightHighContrast = secondaryLight
val onSecondaryLightHighContrast = onSecondaryLight
val secondaryContainerLightHighContrast = secondaryContainerLight
val onSecondaryContainerLightHighContrast = onSecondaryContainerLight
val tertiaryLightHighContrast = tertiaryLight
val onTertiaryLightHighContrast = onTertiaryLight
val tertiaryContainerLightHighContrast = tertiaryContainerLight
val onTertiaryContainerLightHighContrast = onTertiaryContainerLight
val errorLightHighContrast = errorLight
val onErrorLightHighContrast = onErrorLight
val errorContainerLightHighContrast = errorContainerLight
val onErrorContainerLightHighContrast = onErrorContainerLight
val backgroundLightHighContrast = backgroundLight
val onBackgroundLightHighContrast = onBackgroundLight
val surfaceLightHighContrast = surfaceLight
val onSurfaceLightHighContrast = onSurfaceLight
val surfaceVariantLightHighContrast = surfaceVariantLight
val onSurfaceVariantLightHighContrast = onSurfaceVariantLight
val outlineLightHighContrast = outlineLight
val outlineVariantLightHighContrast = outlineVariantLight
val scrimLightHighContrast = scrimLight
val inverseSurfaceLightHighContrast = inverseSurfaceLight
val inverseOnSurfaceLightHighContrast = inverseOnSurfaceLight
val inversePrimaryLightHighContrast = inversePrimaryLight
val surfaceDimLightHighContrast = surfaceDimLight
val surfaceBrightLightHighContrast = surfaceBrightLight
val surfaceContainerLowestLightHighContrast = surfaceContainerLowestLight
val surfaceContainerLowLightHighContrast = surfaceContainerLowLight
val surfaceContainerLightHighContrast = surfaceContainerLight
val surfaceContainerHighLightHighContrast = surfaceContainerHighLight
val surfaceContainerHighestLightHighContrast = surfaceContainerHighestLight

val primaryDarkMediumContrast = primaryDark
val onPrimaryDarkMediumContrast = onPrimaryDark
val primaryContainerDarkMediumContrast = primaryContainerDark
val onPrimaryContainerDarkMediumContrast = onPrimaryContainerDark
val secondaryDarkMediumContrast = secondaryDark
val onSecondaryDarkMediumContrast = onSecondaryDark
val secondaryContainerDarkMediumContrast = secondaryContainerDark
val onSecondaryContainerDarkMediumContrast = onSecondaryContainerDark
val tertiaryDarkMediumContrast = tertiaryDark
val onTertiaryDarkMediumContrast = onTertiaryDark
val tertiaryContainerDarkMediumContrast = tertiaryContainerDark
val onTertiaryContainerDarkMediumContrast = onTertiaryContainerDark
val errorDarkMediumContrast = errorDark
val onErrorDarkMediumContrast = onErrorDark
val errorContainerDarkMediumContrast = errorContainerDark
val onErrorContainerDarkMediumContrast = onErrorContainerDark
val backgroundDarkMediumContrast = backgroundDark
val onBackgroundDarkMediumContrast = onBackgroundDark
val surfaceDarkMediumContrast = surfaceDark
val onSurfaceDarkMediumContrast = onSurfaceDark
val surfaceVariantDarkMediumContrast = surfaceVariantDark
val onSurfaceVariantDarkMediumContrast = onSurfaceVariantDark
val outlineDarkMediumContrast = outlineDark
val outlineVariantDarkMediumContrast = outlineVariantDark
val scrimDarkMediumContrast = scrimDark
val inverseSurfaceDarkMediumContrast = inverseSurfaceDark
val inverseOnSurfaceDarkMediumContrast = inverseOnSurfaceDark
val inversePrimaryDarkMediumContrast = inversePrimaryDark
val surfaceDimDarkMediumContrast = surfaceDimDark
val surfaceBrightDarkMediumContrast = surfaceBrightDark
val surfaceContainerLowestDarkMediumContrast = surfaceContainerLowestDark
val surfaceContainerLowDarkMediumContrast = surfaceContainerLowDark
val surfaceContainerDarkMediumContrast = surfaceContainerDark
val surfaceContainerHighDarkMediumContrast = surfaceContainerHighDark
val surfaceContainerHighestDarkMediumContrast = surfaceContainerHighestDark

val primaryDarkHighContrast = primaryDark
val onPrimaryDarkHighContrast = onPrimaryDark
val primaryContainerDarkHighContrast = primaryContainerDark
val onPrimaryContainerDarkHighContrast = onPrimaryContainerDark
val secondaryDarkHighContrast = secondaryDark
val onSecondaryDarkHighContrast = onSecondaryDark
val secondaryContainerDarkHighContrast = secondaryContainerDark
val onSecondaryContainerDarkHighContrast = onSecondaryContainerDark
val tertiaryDarkHighContrast = tertiaryDark
val onTertiaryDarkHighContrast = onTertiaryDark
val tertiaryContainerDarkHighContrast = tertiaryContainerDark
val onTertiaryContainerDarkHighContrast = onTertiaryContainerDark
val errorDarkHighContrast = errorDark
val onErrorDarkHighContrast = onErrorDark
val errorContainerDarkHighContrast = errorContainerDark
val onErrorContainerDarkHighContrast = onErrorContainerDark
val backgroundDarkHighContrast = backgroundDark
val onBackgroundDarkHighContrast = onBackgroundDark
val surfaceDarkHighContrast = surfaceDark
val onSurfaceDarkHighContrast = onSurfaceDark
val surfaceVariantDarkHighContrast = surfaceVariantDark
val onSurfaceVariantDarkHighContrast = onSurfaceVariantDark
val outlineDarkHighContrast = outlineDark
val outlineVariantDarkHighContrast = outlineVariantDark
val scrimDarkHighContrast = scrimDark
val inverseSurfaceDarkHighContrast = inverseSurfaceDark
val inverseOnSurfaceDarkHighContrast = inverseOnSurfaceDark
val inversePrimaryDarkHighContrast = inversePrimaryDark
val surfaceDimDarkHighContrast = surfaceDimDark
val surfaceBrightDarkHighContrast = surfaceBrightDark
val surfaceContainerLowestDarkHighContrast = surfaceContainerLowestDark
val surfaceContainerLowDarkHighContrast = surfaceContainerLowDark
val surfaceContainerDarkHighContrast = surfaceContainerDark
val surfaceContainerHighDarkHighContrast = surfaceContainerHighDark
val surfaceContainerHighestDarkHighContrast = surfaceContainerHighestDark